//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MADAM.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldValues_StringLong : IFieldValue
    {
        public long ID { get; set; }
        public long ThingID { get; set; }
        public int FieldID { get; set; }
        public int Number { get; set; }
        public string Value { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Thing Thing { get; set; }
    }
}
