//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MADAM.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThingType
    {
        public ThingType()
        {
            this.Fields = new HashSet<Field>();
            this.Things = new HashSet<Thing>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Module { get; set; }
    
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<Thing> Things { get; set; }
    }
}
